- name: Ubuntu Patch Management using shell (no sudo)
  hosts: all
  gather_facts: no
  tasks:
    - name: Run apt update (as normal user)
      shell: echo "Skipping apt update — requires sudo"

    - name: Run apt upgrade (as normal user)
      shell: echo "Skipping apt upgrade — requires sudo"

    - name: Reboot system (as normal user)
      shell: echo "Skipping reboot — requires sudo"
