- name: macOS Patch Management with Homebrew
  hosts: macos_targets
  become: false  # usually unnecessary on macOS for Homebrew tasks
  tasks:
    - name: Ensure Homebrew is installed
      homebrew:
        update_homebrew: yes

    - name: Update brew formulas
      command: brew update
      register: brew_update_output

    - name: Upgrade all Homebrew packages
      command: brew upgrade
      register: brew_upgrade_output

    - name: Cleanup old versions of packages
      command: brew cleanup
