- name: macOS Patch Management with Homebrew
  hosts: all
  become: false  # usually unnecessary on macOS for Homebrew tasks
  tasks:
    - name: Ensure Homebrew is installed
      homebrew:
        update_homebrew: yes

    - name: Update brew formulas
      command: /opt/homebrew/bin/brew update
      register: brew_update_output

    - name: Upgrade all Homebrew packages
      command: /opt/homebrew/bin/brew upgrade
      register: brew_upgrade_output

    - name: Cleanup old versions of packages
      command: /opt/homebrew/bin/brew cleanup
