- name: Ubuntu Patch Management with APT
  hosts: all
  become: false  # needed to run apt as root
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # skip update if last was <1h ago

    - name: Upgrade all installed packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot if kernel was updated
      reboot:
        msg: "Reboot initiated by Ansible after patching."
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
